services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--apiinsecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    image: fernandeeess/portfolio-app:latest
    container_name: webapp


